### ISSUE TITLE
Is there a way to use this without poluting the global scope?

### ISSUE THREAD

**Issue by x2764tech** [ideal-postcodes/ideal-postcodes-core#2]
All the directions seem to be to directly include this in the html, but I want to use it as an ES6 module. 
Is that possible?

**Comment by cblanc** [comment]
Not at the moment. We do intend to support both ES6-style exports and `require` but were planning to roll this up into a number of other backward breaking changes in 2.0.0 for this and the [ideal-postcodes-autcomplete](https://github.com/ideal-postcodes/ideal-postcodes-autocomplete) library

I'll look to get out a working branch of 2.0.0 with just this change this weekend and have it published by Friday

**Comment by x2764tech** [comment]
@cblanc thanks - I can use a cdn version for now (thanks unpkg.com!), but it would be nice not to require another request for this relatively small library.
FYI: I'm using it in an existing React application.

**Comment by cblanc** [comment]
I'm testing it on a number of js bundlers at the moment. Would be great to know which one you're using

**Comment by x2764tech** [comment]
@cblanc I'm using webpack & babel, with <strike>babili/babili-webpack-plugin</strike> babel-minify for production minfication. Happy to give something a try if you need testers.

**Comment by cblanc** [comment]
Hi @x2764tech - I've rebuilt the library to integrate with `require` and `define` in a separate working branch here: https://github.com/ideal-postcodes/ideal-postcodes-core/tree/module_loaders

AMD or CommonJS integration seems to be working on [webpack](https://github.com/kriasoft/react-starter-kit#readme), [browserify](https://github.com/randylien/generator-react-gulp-browserify) and brunch. The library will export itself to window if one of those module systems are not detected.

**Comment by x2764tech** [comment]
@cblanc For my (very simple) use, that works great - both with and without minification - I'm only using the postcode lookup functionality at the moment.

**Comment by cblanc** [comment]
Great, I'll need to do more testing on this before release. So the ETA on 1.0.0 will be Friday or Monday

**Comment by x2764tech** [comment]
Any progress on getting `1.0.0` on <strike>nuget</strike> npm?

EDIT: correct package manager 😊

**Comment by cblanc** [comment]
Hi David, sorry about the wait

We were delayed by a small internal debate (re deprecating global object pollution) and then having to retest it on browserify, webpack and brunch. The main concern is we can see too many developers may ignore the changelog and the major version increment

So while we are supporting commonjs and AMD module systems, the global scope will remain polluted (for now). `IdealPostcodes.removeGlobalReference` is provided to unset the reference

The update is now available on npm as `1.0.0`
